% !TeX TXS-program:compile = txs:///knit2pdf
\documentclass[12pt]{mwart}
\usepackage[utf8]{inputenc}
\usepackage[T1,plmath]{polski}
\usepackage{lmodern}

\usepackage{amssymb}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{amsthm}
\usepackage[hidelinks]{hyperref}
\usepackage{float}

\title{Sprawozdanie 1}
\author{Aleksander Jakóbczyk i Kacper Pasterniak}
\date{}

\begin{document}
	\maketitle 
	
	<<warning=F, message=F,echo = F>>=
    library(binom)
    require(ggplot2)
    library(reshape2)
    library(xtable)
	
    library(vcdExtra)
    library(tidyverse)
    library(matrixStats)


    library(stats)

    # pdf.options(encoding = 'ISOLatin2') # znaki polskie w wykresach
	@
	
	\section*{Lista 5}
        \subsection*{Zad 1}
            \textit{binom.test} - 
\end{document}